### ISSUE TITLE
chlor_a_l3_pass fails to load (duplicate values)

### ISSUE THREAD

**Issue by 7yl4r** [USF-IMARS/erddap-config#1]
The [status page](http://imars-physalis.marine.usf.edu:8080/erddap/status.html) shows that the chlor_a data is failing to load since I tried fixing the lat/lon issue noted over at marinebon/sdg14-shiny#10.

The only thing I see in the logs (`/erddapData/logs/`) that might explain why:

```
...
Duplicates at [2988687] and [2988688] = 18.01288256263424
Duplicates at [2988688] and [2988689] = 18.01288256263424
Duplicates at [2988689] and [2988690] = 18.01288256263424
Duplicates at [2988690] and [2988691] = 18.01288256263424
Duplicates at [2988691] and [2988692] = 18.01288256263424
Duplicates at [2988692] and [2988693] = 18.01288256263424
Duplicates at [2988693] and [2988694] = 18.01288256263424
Duplicates at [2988694] and [2988695] = 18.01288256263424
Duplicates at [2988695] and [2988696] = 18.01288256263424
Duplicates at [2988696] and [2988697] = 18.01288256263424
Duplicates at [2988697] and [2988698] = 18.01288256263424
Duplicates at [2988698] and [2988699] = 18.01288256263424

 at gov.noaa.pfel.erddap.variable.EDVGridAxis.<init>(EDVGridAxis.java:97)
 at gov.noaa.pfel.erddap.variable.EDVLatGridAxis.<init>(EDVLatGridAxis.java:38)
 at gov.noaa.pfel.erddap.dataset.EDDGrid.makeAxisVariable(EDDGrid.java:360)
 at gov.noaa.pfel.erddap.dataset.EDDGridFromFiles.<init>(EDDGridFromFiles.java:1073)
 at gov.noaa.pfel.erddap.dataset.EDDGridFromNcLow.<init>(EDDGridFromNcLow.java:94)
 at gov.noaa.pfel.erddap.dataset.EDDGridFromNcFilesUnpacked.<init>(EDDGridFromNcFilesUnpacked.java:97)
 at gov.noaa.pfel.erddap.dataset.EDDGridFromFiles.fromXml(EDDGridFromFiles.java:272)
 at gov.noaa.pfel.erddap.dataset.EDD.fromXml(EDD.java:392)
 ... 1 more
```

I guess this is saying that there is duplicate lat/lon values for pixels and that is a problem?

**Comment by 7yl4r** [comment]
Is "multiple pixels per 100 trillionth of a degree latitude/longitude" a valid possibility? It doesn't sound valid but I haven't actually done the math.

**Comment by 7yl4r** [comment]
Seeing something different today:
```
==== BEGIN =====================================================================
     To: imarsroot@marine.usf.edu
Subject: 704f7fc38b7b ERDDAP: RunLoadDatasets Stalled
   Date: 2018-10-02T12:25:35+00:00
--------------------------------------------------------------------------------
http://imars-physalis.marine.usf.edu:8080/erddap reports:
RunLoadDatasets is interrupting a stalled LoadDatasets thread (1h 0m 0s > 1h 0m 0s) at 2018-10-02T12:25:35+00:00
==== END =======================================================================
```

**Comment by 7yl4r** [comment]
Attempting to use `DasDds` to diagnose the issue:

```
imars-admin@imars-physalis:~$ sudo docker exec -it erddap  bash -c "cd webapps/erddap/WEB-INF/ && ./DasDds.sh"

////**** ERD Low Level Startup
localTime=2018-10-02T15:27:46+00:00
Java 1.8.0_151 (64 bit, Oracle Corporation) on Linux (4.15.0-34-generic).
MemoryInUse=    10 MB (highWaterMark=    10 MB) (Xmx ~= 958 MB)
logLevel=info: verbose=true reallyVerbose=false
bigParentDirectory=/erddapData/
contextDirectory=/usr/local/tomcat/webapps/erddap/
java.awt.HeadlessException: 
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
 at gov.noaa.pfel.coastwatch.sgt.SgtUtil.isBufferedImageAccelerated(SgtUtil.java:367)
 at gov.noaa.pfel.erddap.util.EDStatic.<clinit>(EDStatic.java:1496)
 at gov.noaa.pfel.erddap.DasDds.<clinit>(DasDds.java:29)


bufferedImage isAccelerated=[unknown]
Custom messages.xml not found at /usr/local/tomcat/content/erddap/messages.xml
Using default messages.xml from  /usr/local/tomcat/webapps/erddap/WEB-INF/classes/gov/noaa/pfel/erddap/util/messages.xml
CfToFromGcmd static loading /usr/local/tomcat/webapps/erddap/WEB-INF/classes/gov/noaa/pfel/erddap/util/CfToGcmd.txt
*** ERD Low Level Startup finished successfully.

logFileMaxSize=20000000
*** Starting DasDds 2018-10-02T15:27:48+00:00
logFile=/erddapData/logs/DasDds.log
Java 1.8.0_151 (64 bit, Oracle Corporation) on Linux (4.15.0-34-generic).
MemoryInUse=    40 MB (highWaterMark=    40 MB) (Xmx ~= 958 MB)

*** DasDds ***
This generates the DAS and DDS for a dataset and puts it in
/erddapData/logs/DasDds.out
Press ^D or ^C to exit at any time.

Which datasetID (default="")
? chlor_a_l3_pass_db6d_37b4_723b

*** DasDds chlor_a_l3_pass_db6d_37b4_723b
*** deleting cached dataset info for datasetID=chlor_a_l3_pass_db6d_37b4_723b
File2.deleteIfOld(/erddapData/dataset/3b/chlor_a_l3_pass_db6d_37b4_723b/) nDir=0 nDeleted=2 nRemain=0

EDD.oneFromDatasetsXml(chlor_a_l3_pass_db6d_37b4_723b)...

*** constructing EDDGridFromFiles(xmlReader)...

*** constructing EDDGridFromFiles chlor_a_l3_pass_db6d_37b4_723b
axis0 ***fileName format=yyyyDDDHHmmss class=double regex=chlor_a_l3_pass_A(\d{13})\.hdf captureGroup=1
dir/file table doesn't exist: /erddapData/dataset/3b/chlor_a_l3_pass_db6d_37b4_723b/dirTable.nc
dir/file table doesn't exist: /erddapData/dataset/3b/chlor_a_l3_pass_db6d_37b4_723b/fileTable.nc
creating new dirTable and fileTable (dirTable=null?true fileTable=null?true badFileMap=null?false)
doQuickRestart=false
4020 files found in /chlor_a_l3_pass/
regex=.*\.hdf recursive=true pathRegex=.* time=107ms
old nBadFiles size=0
sortTime=3ms
old fileTable size=0   nFilesMissing=0
#0 inserted in cache
  var not in file: dataAttributes for dvi=13 name=y
  var not in file: dataAttributes for dvi=14 name=x
#1 inserted in cache
  var not in file: dataAttributes for dvi=13 name=y
  var not in file: dataAttributes for dvi=14 name=x
...

```

**Comment by 7yl4r** [comment]
RAM usage is only at 40%, so I think this OoME is probably java's limit.

**Comment by 7yl4r** [comment]
Trying again w/o x & y:

```
imars-admin@imars-physalis:~$ sudo docker exec -it erddap  bash -c "cd webapps/erddap/WEB-INF/ && bash DasDds.sh chlor_a_l3_pass_db6d_37b4_723b"

////**** ERD Low Level Startup
localTime=2018-10-02T17:07:01+00:00
Java 1.8.0_151 (64 bit, Oracle Corporation) on Linux (4.15.0-34-generic).
MemoryInUse=    10 MB (highWaterMark=    10 MB) (Xmx ~= 958 MB)
logLevel=info: verbose=true reallyVerbose=false
bigParentDirectory=/erddapData/
contextDirectory=/usr/local/tomcat/webapps/erddap/
java.awt.HeadlessException: 
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
 at gov.noaa.pfel.coastwatch.sgt.SgtUtil.isBufferedImageAccelerated(SgtUtil.java:367)
 at gov.noaa.pfel.erddap.util.EDStatic.<clinit>(EDStatic.java:1496)
 at gov.noaa.pfel.erddap.DasDds.<clinit>(DasDds.java:29)


bufferedImage isAccelerated=[unknown]
Custom messages.xml not found at /usr/local/tomcat/content/erddap/messages.xml
Using default messages.xml from  /usr/local/tomcat/webapps/erddap/WEB-INF/classes/gov/noaa/pfel/erddap/util/messages.xml
CfToFromGcmd static loading /usr/local/tomcat/webapps/erddap/WEB-INF/classes/gov/noaa/pfel/erddap/util/CfToGcmd.txt
*** ERD Low Level Startup finished successfully.

logFileMaxSize=20000000
*** Starting DasDds 2018-10-02T17:07:05+00:00
logFile=/erddapData/logs/DasDds.log
Java 1.8.0_151 (64 bit, Oracle Corporation) on Linux (4.15.0-34-generic).
MemoryInUse=    40 MB (highWaterMark=    40 MB) (Xmx ~= 958 MB)

*** DasDds ***
This generates the DAS and DDS for a dataset and puts it in
/erddapData/logs/DasDds.out
Press ^D or ^C to exit at any time.

Which datasetID? chlor_a_l3_pass_db6d_37b4_723b

*** DasDds chlor_a_l3_pass_db6d_37b4_723b
*** deleting cached dataset info for datasetID=chlor_a_l3_pass_db6d_37b4_723b
File2.deleteIfOld(/erddapData/dataset/3b/chlor_a_l3_pass_db6d_37b4_723b/) nDir=0 nDeleted=2 nRemain=0

EDD.oneFromDatasetsXml(chlor_a_l3_pass_db6d_37b4_723b)...

*** constructing EDDGridFromFiles(xmlReader)...

*** constructing EDDGridFromFiles chlor_a_l3_pass_db6d_37b4_723b
axis0 ***fileName format=yyyyDDDHHmmss class=double regex=chlor_a_l3_pass_A(\d{13})\.hdf captureGroup=1
dir/file table doesn't exist: /erddapData/dataset/3b/chlor_a_l3_pass_db6d_37b4_723b/dirTable.nc
dir/file table doesn't exist: /erddapData/dataset/3b/chlor_a_l3_pass_db6d_37b4_723b/fileTable.nc
creating new dirTable and fileTable (dirTable=null?true fileTable=null?true badFileMap=null?false)
doQuickRestart=false
4020 files found in /chlor_a_l3_pass/
regex=.*\.hdf recursive=true pathRegex=.* time=6120ms
old nBadFiles size=0
sortTime=3ms
old fileTable size=0   nFilesMissing=0
#0 inserted in cache
#1 inserted in cache
#2 inserted in cache
...
```

**Comment by 7yl4r** [comment]
Looking at `Xms` & `Xmx` options used on the running processes it looks like the server has a 4GB limit, but DasDds starts up with a 1GB limit.

```
imars-admin@imars-physalis:~$ ps ax | grep java
23322 pts/0    Sl+    0:20 java -cp ./classes:../../../lib/servlet-api.jar:lib/cassandra-driver-core.jar:lib/netty-all.jar:lib/guava.jar:lib/metrics-core.jar:lib/lz4.jar:lib/snappy-java.jar:lib/commons-compress.jar:lib/itext-1.3.1.jar:lib/lucene-core.jar:lib/mail.jar:lib/netcdfAll-latest.jar:lib/slf4j.jar:lib/postgresql.jdbc.jar -Xms1000M -Xmx1000M gov.noaa.pfel.erddap.DasDds chlor_a_l3_pass_db6d_37b4_723b
23542 pts/1    S+     0:00 grep --color=auto java
30404 ?        Ssl  152:53 /docker-java-home/jre/bin/java -Djava.util.logging.config.file=/usr/local/tomcat/conf/logging.properties -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager -server -d64 -Xms4G -Xmx4G -XX:+HeapDumpOnOutOfMemoryError -Djava.awt.headless=true -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled -DerddapContentDirectory=/usr/local/tomcat/content/erddap/ -Djna.tmpdir=/tmp/ -Djava.security.egd=file:/dev/./urandom -Djdk.tls.ephemeralDHKeySize=2048 -Djava.protocol.handler.pkgs=org.apache.catalina.webresources -Dignore.endorsed.dirs= -classpath /usr/local/tomcat/bin/bootstrap.jar:/usr/local/tomcat/bin/tomcat-juli.jar -Dcatalina.base=/usr/local/tomcat -Dcatalina.home=/usr/local/tomcat -Djava.io.tmpdir=/usr/local/tomcat/temp org.apache.catalina.startup.Bootstrap start
```

**Comment by 7yl4r** [comment]
Same issue when using `EDDGridFromNcFiles` instead of `EDDGridFromNcFilesUnpacked`.

**Comment by 7yl4r** [comment]
Good relevant info for further review [on ERDDAP google group](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/erddap/OaX7JjV18pg/sBC0wi3wBgAJ).

**Comment by 7yl4r** [comment]
attempting run with increased memory allocation:

```
imars-admin@imars-physalis:~$ sudo docker exec -it erddap bash -c "cd webapps/erddap/WEB-INF/ && export JAVA_OPTS='-server -Djava.awt.headless=true -Xmx8000M -Xms8000M -d64' && bash DasDds.sh "

////**** ERD Low Level Startup
localTime=2018-10-24T13:50:27+00:00
Java 1.8.0_151 (64 bit, Oracle Corporation) on Linux (4.15.0-36-generic).
MemoryInUse=    10 MB (highWaterMark=    10 MB) (Xmx ~= 958 MB)
logLevel=info: verbose=true reallyVerbose=false
bigParentDirectory=/erddapData/
contextDirectory=/usr/local/tomcat/webapps/erddap/
java.awt.HeadlessException: 
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
 at gov.noaa.pfel.coastwatch.sgt.SgtUtil.isBufferedImageAccelerated(SgtUtil.java:367)
 at gov.noaa.pfel.erddap.util.EDStatic.<clinit>(EDStatic.java:1496)
 at gov.noaa.pfel.erddap.DasDds.<clinit>(DasDds.java:29)


bufferedImage isAccelerated=[unknown]
Custom messages.xml not found at /usr/local/tomcat/content/erddap/messages.xml
Using default messages.xml from  /usr/local/tomcat/webapps/erddap/WEB-INF/classes/gov/noaa/pfel/erddap/util/messages.xml
CfToFromGcmd static loading /usr/local/tomcat/webapps/erddap/WEB-INF/classes/gov/noaa/pfel/erddap/util/CfToGcmd.txt
*** ERD Low Level Startup finished successfully.

logFileMaxSize=20000000
*** Starting DasDds 2018-10-24T13:50:28+00:00
logFile=/erddapData/logs/DasDds.log
Java 1.8.0_151 (64 bit, Oracle Corporation) on Linux (4.15.0-36-generic).
MemoryInUse=    40 MB (highWaterMark=    40 MB) (Xmx ~= 958 MB)
```

**Comment by sebastiandig** [comment]
So I took a look at this problem once again, it seems to be the same problem as the other datasets in the past, needing to have 1 dimensional lat and lon so the variables for the pixels will replace the values for x pixels to lat and the y pixels to lon.

This is an example of the dimensions img_y and img_x are 1D and they become the variable for long and lat. 
```
netcdf AQUA_2019001_2019007_7D_FK_SST4 {
dimensions:
       img_y = 330 ;
       img_x = 660 ; 
variables:
        float longitude(img_x) ;
        float latitude(img_y) ;
```
This is what the current dimension are for the chlor_a files. We get duplicate errors from every x being the same every time it moves one pixel down the row
```
netcdf chlor_a_l3_pass_A2002354191000 {
dimensions:
        y = 1430 ;
        x = 2090 ;
variables: 
      *double lat(y, x) ;*
                lat:units = "degrees_north" ;
                lat:long_name = "latitude coordinate" ;
                lat:standard_name = "latitude" ;
       *double lon(y, x) ;*
                lon:units = "degrees_east" ;
                lon:long_name = "longitude coordinate" ;
                lon:standard_name = "longitude" ;
```

If the lat and lon are vectored I'm sure this will fix the problem for duplicates. I'm not sure how urgent this dataset is, but at least we have something to try when we finally want it in.

**Comment by 7yl4r** [comment]
this issue now out of date
