### ISSUE TITLE
SSTN_2f10_d542_b535 "Outer axis overlap between files"

### ISSUE THREAD

**Issue by 7yl4r** [USF-IMARS/erddap-config#11]
```
[root@imars-dockerhost-dune ~]# sudo docker exec -it axiom-docker-erddap bash -c "cd webapps/erddap/WEB-INF/ && bash DasDds.sh -verbose"
[...]
*** constructing EDDGridFromFiles SSTN_2f10_d542_b535
sourceAxisNames=img_y, img_x
sourceDataNames=sstn_median, sstn_anom
sourceDataTypes=double, double
dir/file table doesn't exist: /erddapData/dataset/35/SSTN_2f10_d542_b535/dirTable.nc
dir/file table doesn't exist: /erddapData/dataset/35/SSTN_2f10_d542_b535/fileTable.nc
creating new dirTable and fileTable (dirTable=null?true fileTable=null?true badFileMap=null?false)
^[[5;7~doQuickRestart=false
428 files found in /srv/imars-objects/fk/MEAN_7D_VSNPP/SSTN/
regex=.*\.nc recursive=true pathRegex=.* time=69ms
old nBadFiles size=0
sortTime=1ms
old fileTable size=0   nFilesMissing=0
#0 file=/srv/imars-objects/fk/MEAN_7D_VSNPP/SSTN/VSNPP_2012019_2012021_7D_FK_SSTN.nc
#0 inserted in cache
#1 file=/srv/imars-objects/fk/MEAN_7D_VSNPP/SSTN/VSNPP_2012022_2012028_7D_FK_SSTN.nc
#1 inserted in cache
[...]
#426 file=/srv/imars-objects/fk/MEAN_7D_VSNPP/SSTN/VSNPP_2020085_2020091_7D_FK_SSTN.nc
#426 inserted in cache
#427 file=/srv/imars-objects/fk/MEAN_7D_VSNPP/SSTN/VSNPP_2020092_2020098_7D_FK_SSTN.nc
#427 inserted in cache
fileTable updated; time=105428ms
2nd sortTime=1ms

  tFileNamePA.size=428
  dirTable.nRows=1
  fileTable.nRows=428
    fileTableInMemory=false
    nUnchanged=0
    nRemoved=0 (nNoLastMod=0, nNoSize=0)
    nReadFile=428 (nDifferentModTime=0 nNew=428) readFileCumTime=1m 44s avg=244ms

*** An error occurred while trying to load SSTN_2f10_d542_b535:
java.lang.RuntimeException: datasets.xml error on or before line #2441: Outer axis overlap between files.
max=652.0 for /srv/imars-objects/fk/MEAN_7D_VSNPP/SSTN/VSNPP_2012019_2012021_7D_FK_SSTN.nc
is greater than
min=0.0 for /srv/imars-objects/fk/MEAN_7D_VSNPP/SSTN/VSNPP_2012022_2012028_7D_FK_SSTN.nc
 at gov.noaa.pfel.erddap.dataset.EDD.fromXml(EDD.java:436)
 at gov.noaa.pfel.erddap.dataset.EDD.oneFromDatasetsXml(EDD.java:517)
 at gov.noaa.pfel.erddap.dataset.EDD.testDasDds(EDD.java:11068)
 at gov.noaa.pfel.erddap.DasDds.doIt(DasDds.java:129)
 at gov.noaa.pfel.erddap.DasDds.main(DasDds.java:155)
Caused by: java.lang.RuntimeException: Outer axis overlap between files.
max=652.0 for /srv/imars-objects/fk/MEAN_7D_VSNPP/SSTN/VSNPP_2012019_2012021_7D_FK_SSTN.nc
is greater than
min=0.0 for /srv/imars-objects/fk/MEAN_7D_VSNPP/SSTN/VSNPP_2012022_2012028_7D_FK_SSTN.nc

 at gov.noaa.pfel.erddap.dataset.EDDGridFromFiles.updateValidateFileTable(EDDGridFromFiles.java:1265)
 at gov.noaa.pfel.erddap.dataset.EDDGridFromFiles.<init>(EDDGridFromFiles.java:1092)
 at gov.noaa.pfel.erddap.dataset.EDDGridFromNcLow.<init>(EDDGridFromNcLow.java:96)
 at gov.noaa.pfel.erddap.dataset.EDDGridFromNcFiles.<init>(EDDGridFromNcFiles.java:104)
 at gov.noaa.pfel.erddap.dataset.EDDGridFromFiles.fromXml(EDDGridFromFiles.java:294)
 at gov.noaa.pfel.erddap.dataset.EDD.fromXml(EDD.java:396)
 ... 4 more
```

**Comment by 7yl4r** [comment]
@dotis : ERDDAP is throwing a "Outer axis overlap between files" error when trying to load your new files. I haven't seen this error before. Is there anything unusual about these files (specifically the VIIRS SSTN files) when compared with the others we have loaded into ERDDAP?

Perhaps VIIRS passes overlap and MODIS do not?

**Comment by 7yl4r** [comment]
The new MODIS and VIIRS images are also not working but I have not yet checked they have the same problem, it could be something else.

Your plan to use different extents should work fine, we can set the limits in grafana.
________________________________

**Comment by 7yl4r** [comment]
Same issue for all the other new datasets too ( SST_66bb_c258_cd59, OC_2a67_61be_9fd6, SST4_aac4_99a3_6549, SST_2963_b743_ee2e ).
