### ISSUE TITLE
DasDds raises "bad file" NullPointer Exception

### ISSUE THREAD

**Issue by 7yl4r** [USF-IMARS/erddap-config#12]
Testing with dataset OC_2a67_61be_9fd6.
Each file fails with the same message below.
I think this error is causing LoadDatasets to crash, resulting in 0 datasets.

```
#432 file=/srv/imars-objects/fk/MEAN_7D_VSNPP/OC/VSNPP_2020113_2020119_7D_FK_OC.nc
#432 inserted in cache
#432 bad file: removing fileTable row for /srv/imars-objects/fk/MEAN_7D_VSNPP/OC/VSNPP_2020113_2020119_7D_FK_OC.nc
java.lang.RuntimeException: Error in EDDGridFromNcFiles.getSourceAxisValues
while getting axisAttributes for variable=***fileName,timeFormat=yyyyDDD,VSNPP_(\d{7})_(\d{7})_7D_FK_OC\.nc,2
from /srv/imars-objects/fk/MEAN_7D_VSNPP/OC/VSNPP_2020113_2020119_7D_FK_OC.nc
Cause: java.lang.NullPointerException
 at gov.noaa.pfel.erddap.dataset.EDDGridFromNcLow.lowGetSourceAxisValues(EDDGridFromNcLow.java:217)
 at gov.noaa.pfel.erddap.dataset.EDDGridFromNcLow.lowGetSourceAxisValues(EDDGridFromNcLow.java:242)
 at gov.noaa.pfel.erddap.dataset.EDDGridFromFiles.getSourceAxisValues(EDDGridFromFiles.java:2028)
 at gov.noaa.pfel.erddap.dataset.EDDGridFromFiles.<init>(EDDGridFromFiles.java:1013)
 at gov.noaa.pfel.erddap.dataset.EDDGridFromNcLow.<init>(EDDGridFromNcLow.java:96)
 at gov.noaa.pfel.erddap.dataset.EDDGridFromNcFiles.<init>(EDDGridFromNcFiles.java:104)
 at gov.noaa.pfel.erddap.dataset.EDDGridFromFiles.fromXml(EDDGridFromFiles.java:294)
 at gov.noaa.pfel.erddap.dataset.EDD.fromXml(EDD.java:396)
 at gov.noaa.pfel.erddap.dataset.EDD.oneFromDatasetsXml(EDD.java:517)
 at gov.noaa.pfel.erddap.dataset.EDD.testDasDds(EDD.java:11068)
 at gov.noaa.pfel.erddap.DasDds.doIt(DasDds.java:129)
 at gov.noaa.pfel.erddap.DasDds.main(DasDds.java:155)
Caused by: java.lang.NullPointerException
 at gov.noaa.pfel.erddap.dataset.EDDGridFromNcLow.lowGetSourceAxisValues(EDDGridFromNcLow.java:217)
 ... 10 more


OC_2a67_61be_9fd6 addBadFile: VSNPP_2020113_2020119_7D_FK_OC.nc
  reason=java.lang.RuntimeException: Error in EDDGridFromNcFiles.getSourceAxisValues
while getting axisAttributes for variable=***fileName,timeFormat=yyyyDDD,VSNPP_(\d{7})_(\d{7})_7D_FK_OC\.nc,2
from /srv/imars-objects/fk/MEAN_7D_VSNPP/OC/VSNPP_2020113_2020119_7D_FK_OC.nc
Cause: java.lang.NullPointerException
 at gov.noaa.pfel.erddap.dataset.EDDGridFromNcLow.lowGetSourceAxisValues(EDDGridFromNcLow.java:217)
```

The files do exist.

**Comment by 7yl4r** [comment]
***fileName axisVariable must be first (aka leftmost)

**Comment by BobSimons** [comment]
Thank you very much for including the error message, the sample file, and the chunk of datasets.xml for the dataset.

This problem occurred because you put the ***fileName axisVariable as the last axisVariable. Instead, a ***fileName axisVariable (if present) must be the first (leftmost) axisVariable.
If you simply change the position of that <axisVariable> chunk in datasets.xml so it is the first axisVariable, the problem goes away and the dataset loads correctly.

The documentation says that a ***fileName axisVariable must be the "leftmost" axisVariable. I see that isn't very clear. I will modify the documentation so that it says it must be the "leftmost (first)" axisVariable.

I hope that helps.
