### ISSUE TITLE
fgbnms_modis_aqua_oc fails to load (var not in file; lat & lon not sorted)

### ISSUE THREAD

**Issue by 7yl4r** [USF-IMARS/erddap-config#2]
From DasDds output:

```
#830 file=/fgbnms_modis_aqua_oc_7d/AQUA_2018211_2018217_7D_FGB_chlor_a.nc
#830 inserted in cache
  var not in file: dataAttributes for dvi=0 name=chlor_a_median
  var not in file: dataAttributes for dvi=1 name=chlor_a_anom
#831 file=/fgbnms_modis_aqua_oc_7d/AQUA_2018218_2018224_7D_FGB_chlor_a.nc
#831 inserted in cache
  var not in file: dataAttributes for dvi=0 name=chlor_a_median
  var not in file: dataAttributes for dvi=1 name=chlor_a_anom
#832 file=/fgbnms_modis_aqua_oc_7d/AQUA_2018225_2018231_7D_FGB_chlor_a.nc
#832 inserted in cache
  var not in file: dataAttributes for dvi=0 name=chlor_a_median
  var not in file: dataAttributes for dvi=1 name=chlor_a_anom
#833 file=/fgbnms_modis_aqua_oc_7d/AQUA_2018232_2018238_7D_FGB_chlor_a.nc
#833 inserted in cache
#834 file=/fgbnms_modis_aqua_oc_7d/AQUA_2018239_2018245_7D_FGB_chlor_a.nc
#834 inserted in cache
#835 file=/fgbnms_modis_aqua_oc_7d/AQUA_2018246_2018252_7D_FGB_chlor_a.nc
#835 inserted in cache
#836 file=/fgbnms_modis_aqua_oc_7d/AQUA_2018253_2018259_7D_FGB_chlor_a.nc
#836 inserted in cache
#837 file=/fgbnms_modis_aqua_oc_7d/AQUA_2018260_2018266_7D_FGB_chlor_a.nc
#837 inserted in cache
#838 file=/fgbnms_modis_aqua_oc_7d/AQUA_2018267_2018273_7D_FGB_chlor_a.nc
#838 inserted in cache
fileTable updated; time=181404ms
2nd sortTime=2ms

  tFileNamePA.size=839
  dirTable.nRows=1
  fileTable.nRows=839
    fileTableInMemory=false
    nUnchanged=0
    nRemoved=0 (nNoLastMod=0, nNoSize=0)
    nReadFile=839 (nDifferentModTime=0 nNew=839) readFileCumTime=2m 54s avg=208ms
Table.saveAsFlatNc /erddapData/dataset/f3/fgbnms_modis_aqua_oc_7d_4a92_09ec_c9f3/dirTable.nc1446910918
  Table.saveAsFlatNc done. TIME=21ms
Table.saveAsFlatNc /erddapData/dataset/f3/fgbnms_modis_aqua_oc_7d_4a92_09ec_c9f3/fileTable.nc1446910918
  Table.saveAsFlatNc done. TIME=43ms
save fileTable(first 5 rows)=
dirIndex,fileList,lastMod,size,nValues,min,max,csvValues,startIndex
0,AQUA_2002225_2002231_7D_FGB_chlor_a.nc,1538159231896,27114129,1,1.0297152E9,1.0297152E9,1.0297152E9,0
0,AQUA_2002232_2002238_7D_FGB_chlor_a.nc,1538159232870,27114129,1,1.03032E9,1.03032E9,1.03032E9,1
0,AQUA_2002239_2002245_7D_FGB_chlor_a.nc,1538159233845,27114129,1,1.0309248E9,1.0309248E9,1.0309248E9,2
0,AQUA_2002246_2002252_7D_FGB_chlor_a.nc,1538159234790,27114129,1,1.0315296E9,1.0315296E9,1.0315296E9,3
0,AQUA_2002253_2002259_7D_FGB_chlor_a.nc,1538159235710,27114129,1,1.0321344E9,1.0321344E9,1.0321344E9,4
...

getting metadataFrom /fgbnms_modis_aqua_oc_7d/AQUA_2018267_2018273_7D_FGB_chlor_a.nc
  ftLastMod first=2018-09-18T19:39:14 last=2018-10-02T17:26:35
  time: DoubleArray isn't evenly spaced: [0]=1.0297152E9, [1]=1.03032E9, spacing=604800.0, average spacing=606862.0525059666.
  smallest spacing=518400.0: [274]=1.1959488E9, [275]=1.1964672E9
  biggest  spacing=777600.0: [122]=1.1036736E9, [123]=1.1044512E9
  longitude: DoubleArray isn't sorted in ascending order: [1099]=-88.01200695334849 > [1100]=-98.0.

*** An error occurred while trying to load fgbnms_modis_aqua_oc_7d_4a92_09ec_c9f3:
java.lang.RuntimeException: datasets.xml error on or before line #185: AxisVariable=longitude isn't sorted.  DoubleArray isn't sorted in ascending order: [1099]=-88.01200695334849 > [1100]=-98.0.  DoubleArray isn't sorted in descending order: [0]=-98.0 < [1]=-97.99091174427055.
 at gov.noaa.pfel.erddap.dataset.EDD.fromXml(EDD.java:429)
 at gov.noaa.pfel.erddap.dataset.EDD.oneFromDatasetsXml(EDD.java:507)
 at gov.noaa.pfel.erddap.dataset.EDD.testDasDds(EDD.java:10746)
 at gov.noaa.pfel.erddap.DasDds.doIt(DasDds.java:125)
 at gov.noaa.pfel.erddap.DasDds.main(DasDds.java:149)
Caused by: java.lang.RuntimeException: AxisVariable=longitude isn't sorted.  DoubleArray isn't sorted in ascending order: [1099]=-88.01200695334849 > [1100]=-98.0.  DoubleArray isn't sorted in descending order: [0]=-98.0 < [1]=-97.99091174427055.
 at gov.noaa.pfel.erddap.variable.EDVGridAxis.<init>(EDVGridAxis.java:89)
 at gov.noaa.pfel.erddap.variable.EDVLonGridAxis.<init>(EDVLonGridAxis.java:38)
 at gov.noaa.pfel.erddap.dataset.EDDGrid.makeAxisVariable(EDDGrid.java:355)
 at gov.noaa.pfel.erddap.dataset.EDDGridFromFiles.<init>(EDDGridFromFiles.java:1073)
 at gov.noaa.pfel.erddap.dataset.EDDGridFromNcLow.<init>(EDDGridFromNcLow.java:94)
 at gov.noaa.pfel.erddap.dataset.EDDGridFromNcFilesUnpacked.<init>(EDDGridFromNcFilesUnpacked.java:97)
 at gov.noaa.pfel.erddap.dataset.EDDGridFromFiles.fromXml(EDDGridFromFiles.java:272)
 at gov.noaa.pfel.erddap.dataset.EDD.fromXml(EDD.java:392)
 ... 4 more
```

Note the "DoubleArray isn't sorted" error as well as the "var not in file" errors.

**Comment by 7yl4r** [comment]
The "var not in file" issue is because something changes (filesize 26M vs 20M) and then changes back mid-way through the dataset:

```
-rwxrwxrwx 1 nobody imars-common 26M Sep 28 18:33 AQUA_2010071_2010077_7D_FGB_chlor_a.nc
-rwxrwxrwx 1 nobody imars-common 20M Sep 18 19:39 AQUA_2010078_2010084_7D_FGB_chlor_a.nc
...
-rwxrwxrwx 1 nobody imars-common 20M Sep 24 20:09 AQUA_2018225_2018231_7D_FGB_chlor_a.nc
-rwxrwxrwx 1 nobody imars-common 26M Oct  2 17:26 AQUA_2018232_2018238_7D_FGB_chlor_a.nc

**Comment by sebastiandig** [comment]
@7yl4r Could you send me the parent directory for this data? I want to look through the meta to see if I can get anymore information. 
       The current directory has 3 different file names come up:
`AQUA_(\d{7})_(\d{7})_7D_FGB_(chlor_a|Rrs_667|nflh)\.nc` 

I'm curious if they are in the same folder and what type of data differences they contain.

**Comment by 7yl4r** [comment]
These are mounted at `/srv/imars-objects/modis_aqua_fgbnms` on the servers.
I just created a symlink to there in your home directory:

```
[root@seashell sebastian]# ln -s /srv/imars-objects/modis_aqua_fgbnms/ ./modis_aqua_fgbnms
[root@seashell sebastian]# chown -h sebastian:imars-common modis_aqua_fgbnms
```

These are (almost) all @dotis 's files so he knows more than I do here.
Here I was trying to load the ones in `./MEAN_7D_AQUA/OC`, but I think the anomaly products (`ANOM_7D_vIOP` and `ANOM_7D_vOC` would be even more valuable to make available.

I also added a [line so the ERDDAP docker container can get to the data](https://github.com/USF-IMARS/imars_puppet/commit/c2a21bf89d5259e7812357009141e4e635500006).

**Comment by sebastiandig** [comment]
I'm working on correcting this, but I think I understand why its giving the error:

`AxisVariable=longitude isn't sorted.  DoubleArray isn't sorted in ascending order: [1099]=-88.01200695334849 > [1100]=-98.0.  DoubleArray isn't sorted in descending order: [0]=-98.0 < [1]=-97.99091174427055.`

For some reason (maybe because it thinks its a globe) that its wrapping the image around on itself. The [1099] corresponds to the last pixel in the image at -88.012... degrees, but its adding a single column of pixels to [1100] which, if wrapped, equals pixel [0] at -98.0 degrees. As for the ascending/descending part, since its trying to display it on a graph, its just trying to change where to origin is. Ascending is like a typical graph starting at (0,0) and going pixel by pixel right and up, while descending starts the origin at the top and going down right. Since it failed the ascend, it tries the descend which it also fails because of the wrapping problem.

I'm looking for some bit of code that could help to tell it not to add a column of pixels, but currently no luck.

**Comment by sebastiandig** [comment]
I think we can close this issue. 
`/srv/imars-objects/modis_aqua_fgbnms/MEAN_7D_AQUA/OC` and `./MEAN_7D_AQUA/SST4` are both on ERDDAP after having the coordinate system vectorized. The other issue with OC about "var not in file" error has been solved by combining the different products into one main file.

**Comment by 7yl4r** [comment]
I can't check from here (I think port 8080 is blocked here), but I am glad you figured this out!
I will close and check when I next have access, and reopen if needed.

:+1:
