### ISSUE TITLE
datasets.xml parsing issue

### ISSUE THREAD

**Issue by 7yl4r** [USF-IMARS/erddap-config#32]
seeing these errors in `log.txt` when using the newly generated `datsets.xml`:

```
ERROR while processing datasets.xml: java.lang.Exception: ERROR in XML file on line #1: The first XML tag="
<?xml version="1.0" encoding="UTF-8" ?>" should have started with "<?xml " and ended with "?>".
 at gov.noaa.pfel.coastwatch.util.SimpleXMLReader.throwException(SimpleXMLReader.java:600)
 at gov.noaa.pfel.coastwatch.util.SimpleXMLReader.<init>(SimpleXMLReader.java:68)
 at gov.noaa.pfel.coastwatch.util.SimpleXMLReader.<init>(SimpleXMLReader.java:108)
 at gov.noaa.pfel.erddap.LoadDatasets.run(LoadDatasets.java:209)


EDStatic.email caught an invalid email address: ERROR: "nobody@example.com" is not a valid email address.
Emailing "72819ffb0f09 ERDDAP: ERROR while processing datasets.xml" to 
```

The first might just be a whitespace issue. The second is more of a warning I think, but should be an easy fix.

**Comment by 7yl4r** [comment]
I can't figure where that `nobody@example.com` address is coming from. Maybe it is a default built into the Java src code... meaning that we need to set some variable (in setup.xml?) that is not being set.

**Comment by 7yl4r** [comment]
Although I wasn't able to figure out the nobody@example.com issue. The server is working now that I have resolved the first issue, so I am closing this.
